# ConcordKV Raft 服务器配置示例

server:
  # 节点标识符
  nodeId: "node1"
  
  # Raft协议监听地址
  listenAddr: ":8080"
  
  # API服务器监听地址  
  apiAddr: ":8081"
  
  # 选举超时时间（毫秒）
  electionTimeout: 5000
  
  # 心跳间隔（毫秒）
  heartbeatInterval: 1000
  
  # 单次追加的最大日志条目数
  maxLogEntries: 100
  
  # 触发快照的日志条目数阈值
  snapshotThreshold: 1000
  
  # 集群节点列表
  peers:
    - "node1:localhost:8080"
    - "node2:localhost:8082" 
    - "node3:localhost:8084"

# 日志配置
logging:
  level: "info"
  file: "logs/raft.log"
  maxSize: 100  # MB
  maxBackups: 3
  compress: true

# 存储配置
storage:
  type: "memory"  # 内存存储
  # type: "file"    # 文件存储
  # dataDir: "data/"
  # syncWrites: true 
# 拓扑服务配置
topology:
  enabled: true
  
  # 健康检查配置
  health_check:
    interval: "30s"
    timeout: "5s"
    retry_count: 3
    failure_threshold: 3
    
  # 事件通知配置
  notifications:
    enable_sse: true
    event_buffer_size: 1000
    subscription_timeout: "300s"
    max_event_history: 1000
    heartbeat_interval: "30s"
    
  # 缓存配置
  cache:
    ttl: "60s"
    refresh_threshold: "30s"
    max_entries: 10000
    compression: true
    
  # 服务器配置
  server:
    max_subscribers: 1000
    snapshot_interval: "60s"
    
# 客户端拓扑配置
topology_client:
  server_urls:
    - "http://localhost:8081"
    - "http://localhost:8082"
    - "http://localhost:8083"
  request_timeout: "10s"
  retry_interval: "5s"
  max_retries: 3
  health_check_period: "30s"
  
  cache_policy:
    ttl: "120s"
    refresh_threshold: "60s"
    max_entries: 5000
    compression_level: 1
